### ISSUE TITLE
Something went wrong , can't load items right now 

### ISSUE THREAD

**Issue by Yahya-khodr** [InolabSF/flutter_voice_chat_using_agora#1]
after I log in , i moved to the room feeds screen , but there is nothing in there , what should I do to create rooms ? 
can you make the data for the room dynamic ?

**Comment by yaizudamashii** [comment]
I wrote in README that you had to create rooms on backend directly, but maybe I will add a functionality to create rooms from the app so we don't have to do backend manipulation.

**Comment by Yahya-khodr** [comment]
If you can add a functionality to create rooms from app , I will be so appreciated , thank you man

**Comment by yaizudamashii** [comment]
OK rooms is a top level key, as with the users
<img width="1253" alt="Screen Shot 2021-04-19 at 11 16 55 AM" src="https://user-images.githubusercontent.com/7308157/115260628-f0fb3900-a100-11eb-88be-dcf9c0be316a.png">

**Comment by Yahya-khodr** [comment]
@yaizudamashii  nice it works , hope you continue your great work with adding room functionality and Agora functionality , thank you !!

**Comment by yaizudamashii** [comment]
Thanks.  Agora stuff is kinda working, if you follow README.  Their Flutter SDK doesn't work as advertised without token, I hope they will fix it soon.

**Comment by Yahya-khodr** [comment]
Yest the it's working , but I couldn't see any speaker tile or mic mute/unmute button inside the roomCard , maybe I still need to test to device to check if the audio works etc..  
 I suggest you to check this repository https://github.com/perpetio/clubhouse , it's not dynamic data , but i think it can be helpful for you , Actually I'm trying to build like clubhouse app , but I'm still new to flutter and don't know a lot about firebase and dynamic maps and data

**Comment by yaizudamashii** [comment]
Oh thanks.  Yeah it is pretty much exactly what I'm trying to do, I'll make a use of it while expanding this repo.

Flutter is great, and it's very easy to work with Firebase.  There are a few tricks to working with Firebase, you need to check if the key exists, then you need to create List<Type> or Map<Type, Type(often dynamic)>.from(data[myKey]) etc.

As a sidenote, Firebase 1.x work great with mobile, but have some problem with Flutter web.  For Flutter web projects I'm using 0.x.

**Comment by Yahya-khodr** [comment]
@yaizudamashii yes I'm trying my best to learn fast , please if you continue to work on that , please mention me so I know , Also If I've done something that benefits your project I will notify you , Thank you Sir !
