### ISSUE TITLE
Collectiong rooms

### ISSUE THREAD

**Issue by Yahya-khodr** [InolabSF/flutter_voice_chat_using_agora#2]
I've added a new collection rooms in firestore , and I've added field title for that document , but still got the error can't load items right now

**Comment by yaizudamashii** [comment]
What is the error you are getting?  Did you make the room have all fields that are defined in the room.dart model?

**Comment by Yahya-khodr** [comment]
I did add rooms collection inside the currentUser document and i only added a title for the auto documentID for the rooms , 
is that all or I have to add more stuffs in there ?

**Comment by Yahya-khodr** [comment]
if you please can add a screenshot for a created collection rooms inside the firestore data .. thank you
